force-app/main/default/objects/Contato_Projeto__c/Contato_Projeto__c.object-meta.xml
<CustomObject>
    <label>Contato Projeto</label>
    <pluralLabel>Contatos Projeto</pluralLabel>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contato_Projeto__c/fields/Email__c.field-meta.xml
<CustomObject>
    <fullname>Email__c</fullname>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomObject>

force-app/main/default/objects/Contato_Projeto__c/fields/Telefone__c.field-meta.xml
<CustomField>
    <fullName>Telefone__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ContatoServiceTest.cls
@isTest
public class ContatoServiceTest {

    @isTest
    static void testCriarContato() {
        Test.startTest();

        Contato_Projeto__c resultado = ContatoService.criarContato(
            'Guilherme Silva', 'gluizdasilva@gmail.com', '24993145766');
        Test.stopTest();

        System.assertNotEquals(null, resultado.Id);
        System.assertEquals('Guilherme Silva', resultado.Name);
        System.assertEquals('gluizdasilva@gmail.com', resultado.Email__c);
        System.assertEquals('24993145766', resultado.Telefone__c);
    }

    @isTest
    static void testListarContatos() {
        insert new Contato_Projeto__c(
            Name= 'Teste',Email__c = 'teste@gmail.com'
        );
        
        Test.startTest();

        List<Contato_Projeto__c> contatos = 
        ContatoService.listarContatos();

        Test.stopTest();

        System.assertEquals(1, contatos.size());
    }
}