force-app/main/default/objects/Contato_Projeto__c/Contato_Projeto__c.object-meta.xml
<CustomObject>
    <label>Contato Projeto</label>
    <pluralLabel>Contatos Projeto</pluralLabel>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contato_Projeto__c/fields/Email__c.field-meta.xml
<CustomObject>
    <fullname>Email__c</fullname>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomObject>

force-app/main/default/objects/Contato_Projeto__c/fields/Telefone__c.field-meta.xml
<CustomField>
    <fullName>Telefone__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ContatoService.cls
public with sharing class ContatoService {

    @AuraEnabled(cacheable=true)
    public static List<Contato_Projeto__c> listarContatos() {
        return [
            SELECT id, Name, Email__c, Telefone__c
            FROM Contato_Projeto__c
            ORDER BY Name ASC
                    ];
    }

    @AuraEnabled
    public static Contato_Projeto__C criarContato(
        String nome, String email, String telefone
    ){
        try {
            Contato_Projeto__c contato = new Contato_Projeto__c(
                Name = nome,
                Email__c = email,
                Telefone__c = telefone
            );
            insert contato;
            return contato;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static Contato_Projeto__C deletarContato(Id contatoId) {
        try {
            Contato_Projeto__c contato = [
                SELECT Id 
                FROM Contato_Projeto__c 
                WHERE Id = :contatoId LIMIT 1];
           
            delete contato;
        }
    }
}